const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGUOT',
    GET_POST_LIMIT: "GET_POST_LIMIT",
    GET_POST_FALSE: "GET_POST_FALSE",

    FEEDBACK: "FEEDBACK",

    // user
    GET_CURRENT: 'GET_CURRENT',
}
export default actionTypes